---
title: "W02D3 Homework"
output: html_notebook
---

1)
```{r}
Thursday <- list("7", "20", "20")
Friday <- list("10", "20", "20")
Saturday <- list("9", "20", "16")

weather <- list(Thursday, Friday, Saturday)
```

2)
```{r}
weather[[1]][2]
weather[[2]][3]
weather[[1]][1]
```

3)
```{r}
temperatures <- list(9, 9, 11, 11, 10, 11, 11, 10, 10, 11, 11, 11, 11, 11)
fourteen_day_forecast <- matrix(temperatures, nrow = 2, ncol = 7, byrow = TRUE)
colnames(fourteen_day_forecast) <- list("Thursday", "Friday", "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday")
rownames(fourteen_day_forecast) <- list("Week_1", "Week_2")

fourteen_day_forecast
```
4)
```{r}
fourteen_day_forecast[2, 3]
```
```{r}
fourteen_day_forecast[2, 1:7]
```
```{r}
fourteen_day_forecast[1:2, 1]
fourteen_day_forecast[1:2, 3]
fourteen_day_forecast[1:2, 5]
```
```{r}
answers <- function(x) {
  if (is.character(x) == TRUE) {
    return(str_c("The answer is: ", x))
  }
  if (is.numeric(x) == TRUE & x < 10) {
    return(x)
  }
  if (is.numeric(x) == TRUE & x > 10) {
    return(x/10)
  } else {
    return("Invalid input")
  }
}
```

```{r}
answers("wow!")
answers(10)
```
6)
```{r}
check_vector <- function(x, y) {
  if (all(x == y)) {
    return("Exactly the same")
  }
  if (any(x != y)) {
    x <- sort(x)
    x <- sort(y)
    if (all(x == y)) {
      return("The same")
    }
      return("Different")
  }
}
  
```

```{r}
v1 <- c(4, 5, 6)
v2 <- c(1, 2, 3)

check_vector(v1, v2)
```


```{r}
debug(check_vector)

check_vector(v1,v2)
```
```{r}
undebug(check_vector)
```





