---
title: "R Notebook"
output: html_notebook
---

## W06D2 Homework

1)
```{r}
library(tidyverse)
library(janitor)

items <- read_csv("20190928-items.csv") %>% 
  clean_names()
```
```{r}
items
```

2) Samsung - 397
```{r}
items %>% 
  group_by(brand) %>% 
  summarise(num = n()) %>% 
  slice_max(num)
```

3)
```{r}
samsung_stats <- items %>%
  filter(brand == "Samsung") %>% 
  summarise(
    num = n(),
    mean = mean(rating),
    sd = sd(rating)
  )

samsung_summary <- items %>% 
  filter(brand == "Samsung") %>% 
  ggplot(aes(x = rating)) +
  geom_histogram(aes(y = after_stat(density)), col = "white", fill = "springgreen4") +
  stat_function(
    fun = dnorm,
    args = list(
      mean = samsung_stats$mean,
      sd = samsung_stats$sd
    ),
    col = "firebrick"
  )

samsung_summary
```

4)
```{r}
samsung_summary %>%
  filter(rating >= samsung_stats$mean - samsung_stats$sd) %>%
  filter(rating <= samsung_stats$mean + samsung_stats$sd) %>%
  summarise(prop_within_1sd = n() / nrow(samsung_summary))
```

