---
title: "R Notebook"
output: html_notebook
---

# CI's homework

1)
```{r}
library(tidyverse)
library(janitor)
library(infer)

ames <- read_csv("day_03/ames.csv") %>% 
  clean_names()
```

2) the distribution is slightly normal but heavily right skewed
```{r}
ames %>% 
  select(lot_area) %>% 
  ggplot(aes(x = lot_area)) +
  geom_histogram(binwidth = 1500, colour = "white", fill = "green4")
```
3)
```{r}
lot_resample_200 <- ames %>% 
  rep_sample_n(size = 200, replace = TRUE, reps = 5000) %>% 
  summarise(
    mean_lot_area = mean(lot_area)
  )
```


```{r}
lot_resample_200 %>% 
  ggplot() +
  aes(x = mean_lot_area) +
  geom_histogram(colour = "white", fill = "pink4")
```
4)
```{r}
infer_resample <- lot_resample_200 %>% 
  specify(response = mean_lot_area) %>% 
  generate(reps = 5000, type = "bootstrap") %>% 
  calculate(stat = "mean")
```


```{r}
lot_ci_95 <- infer_resample %>% 
  get_confidence_interval(level = 0.95, type = "percentile")

lot_ci_95
```

```{r}
infer_resample %>%
  visualise() +
  shade_confidence_interval(endpoints = lot_ci_95)
```

5) it covers a broader area of the graph as it includes more variables
```{r}
lot_ci_99 <- infer_resample %>% 
  get_confidence_interval(level = 0.99, type = "percentile")

lot_ci_99
```

```{r}
infer_resample %>%
  visualise() +
  shade_confidence_interval(endpoints = lot_ci_99)
```

6)
```{r}
mean_infer <- infer_resample %>% 
  summarise(mean = mean(stat))

mean_infer
```



