---
title: "R Notebook"
output: html_notebook
---

```{r}
library(gtools)
library(tidyverse)
source("day_01/prob.R")

titanic <- read_csv("titanic.csv")

titanic
```

```{r}
titanic <- titanic %>% 
  mutate(crew = case_when(
    class == "3rd" ~ "passenger",
    class == "2nd" ~ "passenger",
    class == "1st" ~ "passenger",
    class == "engineering crew" ~ "crew",
    class == "victualling crew" ~ "crew",
    class == "restaurant staff" ~ "crew",
    class == "deck crew" ~ "crew"
  ))

titanic
```

```{r}
cont_table <- titanic %>% 
  tabyl(crew, survived)

cont_table
```

```{r}
cont_table %>% 
  adorn_totals(where = c("row", "col")) %>% 
  adorn_percentages(denominator = "all")
```
p(survived GIVEN crew) = p(survived AND crew) / p(survived)

```{r}
0.09560489/0.32215677
```
p(survived GIVEN passenger) = p(survived AND passenger) / p(survived)

```{r}
0.22655188/0.32215677
```
Passengers are more likely to survive than crew

## Consolidation questions

1) 5/6

2) 6x6x6 = 36

3i) 34
```{r}
four_die <- rolldie(4)

four_die %>% 
  filter(X1 + X2 + X3 + X4 == 5 | X1 + X2 + X3 + X4 == 6 | X1 + X2 + X3 + X4 == 7) %>% 
  nrow()
```

3ii) 0.026
```{r}
34/nrow(four_die)
```

4) 1/120 = 0.0083
```{r}
people <- c("A", "B", "C", "D", "E")

chairs <- as_tibble(permutations(n = 5, r = 5, people, repeats.allowed = FALSE))

chairs
```

5i) 1/720 = 0.001
```{r}
dice <- c(1, 2, 3, 4, 5, 6)

rolls <- as_tibble(permutations(n = 6, r = 6, dice, repeats.allowed = FALSE))

rolls
```
5ii) 
```{r}
rolls2 <- as_tibble(combinations(n = 6, r = 6, dice))

rolls2
```

6)p(spade GIVEN black) = p(spade AND black)/ p(spade)

```{r}

cards_table <- cards %>%
  mutate(black = case_when(
    suit == "Club" ~ TRUE,
    suit == "Diamond" ~ FALSE,
    suit == "Heart" ~ FALSE,
    suit == "Spade" ~ TRUE
  )) %>% 
  tabyl(suit, black)

prob_cards <- cards_table %>% 
  adorn_totals(where = c("row", "col")) %>% 
  adorn_percentages(denominator = "all")

prob_cards
```
```{r}
0.25/ 0.25
```







